/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "gpio.h"
#include "uart.h"
#include <stdio.h>
#include "timer.h"

// Macros





int main(void)
{

	timer_init(&TIMER_3);
	timer_init(&TIMER_2);

	uint8_t timer3Flag = 0;
	uint8_t timer2Flag = 0;
	uint8_t timer3Status = 0;
	uint8_t timer2Status = 0;


	usart2_init();





    while(1)
    {

    	timer3Status = startTimer(65537U, &TIMER_3);
    	timer2Status = startTimer(5000U, &TIMER_2);

    	if(timer3Status == 1)
    	{
    		while(timer3Flag == 0)
    		{
    			timer3Flag = check_timer_flag(&TIMER_3);
    		}

    		toggle_pa5_led();

    	}

    	if(timer2Status == 1)
    	{

    		while(timer2Flag == 0)
    		{
    		    timer2Flag = check_timer_flag(&TIMER_2);
    		}

    		 toggle_pa5_led();
    		 timer2Flag = 0;

    	}








    }

    return 0;


}
